# Generated by Django 4.1.7 on 2023-03-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_code', models.IntegerField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50, verbose_name='Station Name')),
                ('station_photo', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_station', models.CharField(max_length=30)),
                ('to_station', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('seat', models.IntegerField()),
                ('seat_class', models.CharField(max_length=10)),
                ('fare', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tain Name')),
                ('seat', models.IntegerField()),
                ('start', models.TimeField()),
                ('finish', models.TimeField()),
                ('trip_type', models.CharField(choices=[('UP', 'up'), ('DOWN', 'down')], max_length=30)),
                ('date', models.DateField(blank=True)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_from', to='ticket_booking.station')),
                ('to_staion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_to', to='ticket_booking.station')),
            ],
        ),
    ]
