# Generated by Django 4.1.7 on 2023-03-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
