# Generated by Django 4.1.7 on 2023-03-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0003_remove_station_station_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Train Name'),
        ),
    ]
