# Generated by Django 4.1.7 on 2023-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0005_rename_to_staion_train_to_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('tickets', models.PositiveIntegerField(default=1)),
                ('coach', models.CharField(max_length=30)),
                ('cost', models.PositiveIntegerField(default=10)),
                ('total_cost', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='payment',
        ),
    ]
