# Generated by Django 4.1.7 on 2023-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0006_ticket_remove_trip_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
