# Generated by Django 4.1.7 on 2023-03-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0007_ticket_time_trip_payment_alter_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
